Update AirPluginTool.groovy
Fix issues with final def after UCD v7.2 moved to groovy 3 causing error.

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/opt/IBM/ibm-ucd/agent/var/plugins/com.ibm.datapower_21_c161d6fcc56f21d3ce0c76843d79fb8938d175ab1c312601b59cce03dd6d456d/classes/com/urbancode/air/AirPluginTool.groovy: 49: The variable [inputPropsStream] is declared final but is reassigned
. At [49:13]  @ line 49, column 13.
               inputPropsStream = new FileInputStream(inputPropsFile);
               ^

1 error